feat: major and minor tags
atomicfi/action-release-action pull request #21
Opened 2022-07-21 22:52 UTC by JacobPuff-Atomicfi

Now creates/updates major and minor tags.

For PA-105

2022-07-21 23:36 UTC, mreysser requested changes

2022-07-21 23:36 UTC, mreysser commented on action.yaml
> +      uses: sersoft-gmbh/running-release-tags-action@v2
Something Ronny has suggested is to look at how many stars a given action has. This one has very few. I'm not opposed to using it, but I suggest fixing to a specific tag so that future changes upstream don't break our workflow.
```suggestion
      uses: sersoft-gmbh/running-release-tags-action@v2.1.0
```

2022-07-22 16:46 UTC, JacobPuff-Atomicfi commented on action.yaml
> +      uses: sersoft-gmbh/running-release-tags-action@v2
I've committed the change, but I would rather base the decision off of the number of users rather than stars. I've never used the star feature, and I don't think an action would be where people would.

2022-07-22 21:39 UTC, mreysser approved these changes
Hmm, maybe I missed that - how does one check how many people are using an action?

2022-07-25 15:50 UTC, JacobPuff-Atomicfi commented
> Hmm, maybe I missed that - how does one check how many people are using an action?

You can _sometimes_ see it on the side bar. Or you can go to the insights tab > dependency graph > dependents.
[Example for the mentioned action](https://github.com/sersoft-gmbh/running-release-tags-action/network/dependents?package_id=UGFja2FnZS0yOTQ0NzAxMDQw)

2022-07-25 15:50 UTC, merged